AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Land Registartion Project

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: LandRegistartionApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DependencyLayer
      Description: Shared libraries for Lambda functions
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.12

  AtomicFeederFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./AtomicFeederFunction
      Description: Function to write data to DynamoDB
      Environment:
        Variables:
          TABLE_NAME: !Ref LandRecordTable
      Layers:
        - !Ref DependencyLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LandRecordTable
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Description: Runs every Friday at 16 UTC/9AM PST
            Schedule: cron(0 16 ? * FRI *)
        WriteToDynamoDBAPI:
          Type: Api
          Properties:
            Path: /feeder
            Method: POST
            RestApiId: !Ref MyApi
            Auth:
              None: {}

  LandRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./LandRecordFunction
      Environment:
        Variables:
          TABLE_NAME: !Ref LandRecordTable
      Layers:
        - !Ref DependencyLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LandRecordTable
      Events:
        LandRecordAPI:
          Type: Api
          Properties:
            Path: /land
            Method: GET
            RestApiId: !Ref MyApi
            Auth:
              None: {}

  CitizenFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./CitizenFeedbackFunction
      Environment:
        Variables:
          TABLE_NAME: !Ref CitizenFeedbackTable
      Layers:
        - !Ref DependencyLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CitizenFeedbackTable
      Events:
        FeedbackAPI:
          Type: Api
          Properties:
            Path: /feedback
            Method: POST
            RestApiId: !Ref MyApi
            Auth:
              None: {}

  LandRecordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: LandRecords
      AttributeDefinitions:
        - AttributeName: record_id
          AttributeType: S
      KeySchema:
        - AttributeName: record_id
          KeyType: HASH

  CitizenFeedbackTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: CitizenFeedbackTable
      PrimaryKey:
        Name: feedback_id
        Type: String

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "land-registartion-frontend-${AWS::AccountId}-${AWS::Region}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

Outputs:

  WebsiteURL:
    Value: !GetAtt FrontendBucket.WebsiteURL
    Description: Public URL for your frontend

  AtomicFeederFunctionAPI:
    Description: "Data feeder for land registration details."
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feeder"

  LandRecordFunctionAPI:
    Description: "API for land record management."
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/land"

  CitizenFeedbackFunctionAPI:
    Description: "API for citizen feedback."
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feedback"
